version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/questionario_hablab
      - ./data:/var/lib/sqlite
    environment:
      - .env

  db:
    image: "postgres:13-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
