"""empty message

Revision ID: d904b2a842a7
Revises: 
Create Date: 2024-04-17 15:32:35.235698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd904b2a842a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respostas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tel', sa.VARCHAR(length=4), nullable=False),
    sa.Column('em_casa', sa.VARCHAR(length=3), nullable=False),
    sa.Column('comodo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('temperatura', sa.VARCHAR(length=50), nullable=False),
    sa.Column('preferencia', sa.VARCHAR(length=50), nullable=False),
    sa.Column('consideracao', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vestimenta', sa.VARCHAR(length=50), nullable=False),
    sa.Column('atividade', sa.VARCHAR(length=200), nullable=False),
    sa.Column('situacao', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
